export const CATEGORY_PROGRESSIONS: Record<
  string,
  { level: number; title: string; requiredTILs: number }[]
> = {
  science: [
    { level: 1, title: "Graduate Scientist", requiredTILs: 10 },
    { level: 2, title: "Board Certified Scientist", requiredTILs: 25 },
    { level: 3, title: "Lab Pioneer", requiredTILs: 50 },
    { level: 4, title: "Scientific Visionary", requiredTILs: 100 },
    { level: 5, title: "Quantum Mind", requiredTILs: 250 },
    { level: 6, title: "Einstein Reincarnated", requiredTILs: 1000 },
  ],
  mindset: [
    { level: 1, title: "Growth Seeker", requiredTILs: 10 },
    { level: 2, title: "Thoughtful Thinker", requiredTILs: 25 },
    { level: 3, title: "Perspective Shifter", requiredTILs: 50 },
    { level: 4, title: "Reflective Practitioner", requiredTILs: 100 },
    { level: 5, title: "Inner Architect", requiredTILs: 250 },
    { level: 6, title: "Master of Mindsets", requiredTILs: 1000 },
  ],
  history: [
    { level: 1, title: "History Buff", requiredTILs: 10 },
    { level: 2, title: "Time Traveler", requiredTILs: 25 },
    { level: 3, title: "Storykeeper", requiredTILs: 50 },
    { level: 4, title: "Context Architect", requiredTILs: 100 },
    { level: 5, title: "Epoch Explorer", requiredTILs: 250 },
    { level: 6, title: "Keeper of Time", requiredTILs: 1000 },
  ],
  health: [
    { level: 1, title: "Wellness Novice", requiredTILs: 10 },
    { level: 2, title: "Health Enthusiast", requiredTILs: 25 },
    { level: 3, title: "Body & Mind Advocate", requiredTILs: 50 },
    { level: 4, title: "Holistic Healer", requiredTILs: 100 },
    { level: 5, title: "Wellness Strategist", requiredTILs: 250 },
    { level: 6, title: "Sage of Health", requiredTILs: 1000 },
  ],
  tech: [
    { level: 1, title: "Digital Tinkerer", requiredTILs: 10 },
    { level: 2, title: "Code Explorer", requiredTILs: 25 },
    { level: 3, title: "Systems Thinker", requiredTILs: 50 },
    { level: 4, title: "Tech Strategist", requiredTILs: 100 },
    { level: 5, title: "Full Stack Sage", requiredTILs: 250 },
    { level: 6, title: "Architect of the Future", requiredTILs: 1000 },
  ],
  math: [
    { level: 1, title: "Number Cruncher", requiredTILs: 10 },
    { level: 2, title: "Equation Explorer", requiredTILs: 25 },
    { level: 3, title: "Pattern Seeker", requiredTILs: 50 },
    { level: 4, title: "Logical Thinker", requiredTILs: 100 },
    { level: 5, title: "Mathematical Alchemist", requiredTILs: 250 },
    { level: 6, title: "Theorem Architect", requiredTILs: 1000 },
  ],
  environment: [
    { level: 1, title: "Eco Learner", requiredTILs: 10 },
    { level: 2, title: "Planet Protector", requiredTILs: 25 },
    { level: 3, title: "Sustainability Seeker", requiredTILs: 50 },
    { level: 4, title: "Green Advocate", requiredTILs: 100 },
    { level: 5, title: "Earth Strategist", requiredTILs: 250 },
    { level: 6, title: "Guardian of the Wild", requiredTILs: 1000 },
  ],
  design: [
    { level: 1, title: "Aesthetic Explorer", requiredTILs: 10 },
    { level: 2, title: "Visual Thinker", requiredTILs: 25 },
    { level: 3, title: "Design Strategist", requiredTILs: 50 },
    { level: 4, title: "Systems Stylist", requiredTILs: 100 },
    { level: 5, title: "Creative Director", requiredTILs: 250 },
    { level: 6, title: "Design Philosopher", requiredTILs: 1000 },
  ],
  innovation: [
    { level: 1, title: "Idea Collector", requiredTILs: 10 },
    { level: 2, title: "Problem Solver", requiredTILs: 25 },
    { level: 3, title: "Disruptive Thinker", requiredTILs: 50 },
    { level: 4, title: "Inventive Mind", requiredTILs: 100 },
    { level: 5, title: "Innovation Architect", requiredTILs: 250 },
    { level: 6, title: "Visionary Creator", requiredTILs: 1000 },
  ],
  communication: [
    { level: 1, title: "Active Listener", requiredTILs: 10 },
    { level: 2, title: "Clear Messenger", requiredTILs: 25 },
    { level: 3, title: "Persuasion Student", requiredTILs: 50 },
    { level: 4, title: "Strategic Communicator", requiredTILs: 100 },
    { level: 5, title: "Story Architect", requiredTILs: 250 },
    { level: 6, title: "Voice of the People", requiredTILs: 1000 },
  ],
  culture: [
    { level: 1, title: "Arts Aficionado", requiredTILs: 10 },
    { level: 2, title: "Cultural Curator", requiredTILs: 25 },
    { level: 3, title: "Global Citizen", requiredTILs: 50 },
    { level: 4, title: "Heritage Explorer", requiredTILs: 100 },
    { level: 5, title: "Narrative Weaver", requiredTILs: 250 },
    { level: 6, title: "Guardian of Culture", requiredTILs: 1000 },
  ],
  travel: [
    { level: 1, title: "Language Wanderer", requiredTILs: 10 },
    { level: 2, title: "Phrase Collector", requiredTILs: 25 },
    { level: 3, title: "Culture Connector", requiredTILs: 50 },
    { level: 4, title: "Fluent Explorer", requiredTILs: 100 },
    { level: 5, title: "Multilingual Mind", requiredTILs: 250 },
    { level: 6, title: "Global Interpreter", requiredTILs: 1000 },
  ],
  philosophy: [
    { level: 1, title: "Questioner", requiredTILs: 10 },
    { level: 2, title: "Thought Explorer", requiredTILs: 25 },
    { level: 3, title: "Ethical Seeker", requiredTILs: 50 },
    { level: 4, title: "Logic Builder", requiredTILs: 100 },
    { level: 5, title: "Meta Thinker", requiredTILs: 250 },
    { level: 6, title: "Philosopher King/Queen", requiredTILs: 1000 },
  ],
};
